# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Install node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    
    - name: Install OpenAPI generator CLI
      run: |
        sudo npm install @openapitools/openapi-generator-cli -g

    - name: Convert API spec to HTML
      run: |
        DOC_OUTPUT=$(mktemp -d)
        openapi-generator generate -g html2 -i ./api.yaml -o "${DOC_OUTPUT}"

    - name: Update gh-pages branch
      run: |
        git checkout gh-pages
        rm -rf ./*
        mv "${DOC_OUTPUT}/*" ./
        git commit -m "Update doc"

    - name: Push doc to git page
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.HEADLESS_TOKEN }}
        branch: gh-pages
